//
// A proto file defining the Param and Result types for QueryService.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: query.proto

package pbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *****************************************
// Definitions of Param and Result types for productCategory search.
// *****************************************
type CategoryParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryParam) Reset() {
	*x = CategoryParam{}
	mi := &file_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryParam) ProtoMessage() {}

func (x *CategoryParam) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryParam.ProtoReflect.Descriptor instead.
func (*CategoryParam) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{0}
}

func (x *CategoryParam) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CategoriesResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoriesResult) Reset() {
	*x = CategoriesResult{}
	mi := &file_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoriesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoriesResult) ProtoMessage() {}

func (x *CategoriesResult) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoriesResult.ProtoReflect.Descriptor instead.
func (*CategoriesResult) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{1}
}

func (x *CategoriesResult) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *CategoriesResult) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CategoriesResult) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type CategoryResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*CategoryResult_Category
	//	*CategoryResult_Error
	Result        isCategoryResult_Result `protobuf_oneof:"result"`
	Timestamp     *timestamppb.Timestamp  `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryResult) Reset() {
	*x = CategoryResult{}
	mi := &file_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryResult) ProtoMessage() {}

func (x *CategoryResult) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryResult.ProtoReflect.Descriptor instead.
func (*CategoryResult) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{2}
}

func (x *CategoryResult) GetResult() isCategoryResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CategoryResult) GetCategory() *Category {
	if x != nil {
		if x, ok := x.Result.(*CategoryResult_Category); ok {
			return x.Category
		}
	}
	return nil
}

func (x *CategoryResult) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*CategoryResult_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *CategoryResult) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type isCategoryResult_Result interface {
	isCategoryResult_Result()
}

type CategoryResult_Category struct {
	Category *Category `protobuf:"bytes,1,opt,name=category,proto3,oneof"`
}

type CategoryResult_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CategoryResult_Category) isCategoryResult_Result() {}

func (*CategoryResult_Error) isCategoryResult_Result() {}

// *****************************************
// Definitions of Param and Result types for product search.
// *****************************************
type ProductParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductParam) Reset() {
	*x = ProductParam{}
	mi := &file_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductParam) ProtoMessage() {}

func (x *ProductParam) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductParam.ProtoReflect.Descriptor instead.
func (*ProductParam) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{3}
}

func (x *ProductParam) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductParam) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type ProductsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductsResult) Reset() {
	*x = ProductsResult{}
	mi := &file_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsResult) ProtoMessage() {}

func (x *ProductsResult) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsResult.ProtoReflect.Descriptor instead.
func (*ProductsResult) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{4}
}

func (x *ProductsResult) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ProductsResult) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ProductsResult) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ProductResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ProductResult_Product
	//	*ProductResult_Error
	Result        isProductResult_Result `protobuf_oneof:"result"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResult) Reset() {
	*x = ProductResult{}
	mi := &file_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResult) ProtoMessage() {}

func (x *ProductResult) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResult.ProtoReflect.Descriptor instead.
func (*ProductResult) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{5}
}

func (x *ProductResult) GetResult() isProductResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ProductResult) GetProduct() *Product {
	if x != nil {
		if x, ok := x.Result.(*ProductResult_Product); ok {
			return x.Product
		}
	}
	return nil
}

func (x *ProductResult) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*ProductResult_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ProductResult) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type isProductResult_Result interface {
	isProductResult_Result()
}

type ProductResult_Product struct {
	Product *Product `protobuf:"bytes,1,opt,name=product,proto3,oneof"`
}

type ProductResult_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ProductResult_Product) isProductResult_Result() {}

func (*ProductResult_Error) isProductResult_Result() {}

var File_query_proto protoreflect.FileDescriptor

const file_query_proto_rawDesc = "" +
	"\n" +
	"\vquery.proto\x12\bproto.v1\x1a\verror.proto\x1a\fmodels.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1f\n" +
	"\rCategoryParam\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa7\x01\n" +
	"\x10CategoriesResult\x122\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x12.proto.v1.CategoryR\n" +
	"categories\x12%\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.proto.v1.ErrorR\x05error\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xaf\x01\n" +
	"\x0eCategoryResult\x120\n" +
	"\bcategory\x18\x01 \x01(\v2\x12.proto.v1.CategoryH\x00R\bcategory\x12'\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.proto.v1.ErrorH\x00R\x05error\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB\b\n" +
	"\x06result\"8\n" +
	"\fProductParam\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\"\xa0\x01\n" +
	"\x0eProductsResult\x12-\n" +
	"\bproducts\x18\x01 \x03(\v2\x11.proto.v1.ProductR\bproducts\x12%\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.proto.v1.ErrorR\x05error\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xab\x01\n" +
	"\rProductResult\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x11.proto.v1.ProductH\x00R\aproduct\x12'\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.proto.v1.ErrorH\x00R\x05error\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB\b\n" +
	"\x06result2\x86\x01\n" +
	"\rCategoryQuery\x12:\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a\x1a.proto.v1.CategoriesResult\x129\n" +
	"\x04ById\x12\x17.proto.v1.CategoryParam\x1a\x18.proto.v1.CategoryResult2\xfb\x01\n" +
	"\fProductQuery\x129\n" +
	"\n" +
	"ListStream\x12\x16.google.protobuf.Empty\x1a\x11.proto.v1.Product0\x01\x128\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a\x18.proto.v1.ProductsResult\x127\n" +
	"\x04ById\x12\x16.proto.v1.ProductParam\x1a\x17.proto.v1.ProductResult\x12=\n" +
	"\tByKeyword\x12\x16.proto.v1.ProductParam\x1a\x18.proto.v1.ProductsResultB\x9a\x01\n" +
	"\fcom.proto.v1B\n" +
	"QueryProtoP\x01Z=github.com/tortillaproduction/go-microservices/api/pb/v1;pbv1\xa2\x02\x03PXX\xaa\x02\bProto.V1\xca\x02\bProto\\V1\xe2\x02\x14Proto\\V1\\GPBMetadata\xea\x02\tProto::V1b\x06proto3"

var (
	file_query_proto_rawDescOnce sync.Once
	file_query_proto_rawDescData []byte
)

func file_query_proto_rawDescGZIP() []byte {
	file_query_proto_rawDescOnce.Do(func() {
		file_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)))
	})
	return file_query_proto_rawDescData
}

var file_query_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_query_proto_goTypes = []any{
	(*CategoryParam)(nil),         // 0: proto.v1.CategoryParam
	(*CategoriesResult)(nil),      // 1: proto.v1.CategoriesResult
	(*CategoryResult)(nil),        // 2: proto.v1.CategoryResult
	(*ProductParam)(nil),          // 3: proto.v1.ProductParam
	(*ProductsResult)(nil),        // 4: proto.v1.ProductsResult
	(*ProductResult)(nil),         // 5: proto.v1.ProductResult
	(*Category)(nil),              // 6: proto.v1.Category
	(*Error)(nil),                 // 7: proto.v1.Error
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*Product)(nil),               // 9: proto.v1.Product
	(*emptypb.Empty)(nil),         // 10: google.protobuf.Empty
}
var file_query_proto_depIdxs = []int32{
	6,  // 0: proto.v1.CategoriesResult.categories:type_name -> proto.v1.Category
	7,  // 1: proto.v1.CategoriesResult.error:type_name -> proto.v1.Error
	8,  // 2: proto.v1.CategoriesResult.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 3: proto.v1.CategoryResult.category:type_name -> proto.v1.Category
	7,  // 4: proto.v1.CategoryResult.error:type_name -> proto.v1.Error
	8,  // 5: proto.v1.CategoryResult.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 6: proto.v1.ProductsResult.products:type_name -> proto.v1.Product
	7,  // 7: proto.v1.ProductsResult.error:type_name -> proto.v1.Error
	8,  // 8: proto.v1.ProductsResult.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 9: proto.v1.ProductResult.product:type_name -> proto.v1.Product
	7,  // 10: proto.v1.ProductResult.error:type_name -> proto.v1.Error
	8,  // 11: proto.v1.ProductResult.timestamp:type_name -> google.protobuf.Timestamp
	10, // 12: proto.v1.CategoryQuery.List:input_type -> google.protobuf.Empty
	0,  // 13: proto.v1.CategoryQuery.ById:input_type -> proto.v1.CategoryParam
	10, // 14: proto.v1.ProductQuery.ListStream:input_type -> google.protobuf.Empty
	10, // 15: proto.v1.ProductQuery.List:input_type -> google.protobuf.Empty
	3,  // 16: proto.v1.ProductQuery.ById:input_type -> proto.v1.ProductParam
	3,  // 17: proto.v1.ProductQuery.ByKeyword:input_type -> proto.v1.ProductParam
	1,  // 18: proto.v1.CategoryQuery.List:output_type -> proto.v1.CategoriesResult
	2,  // 19: proto.v1.CategoryQuery.ById:output_type -> proto.v1.CategoryResult
	9,  // 20: proto.v1.ProductQuery.ListStream:output_type -> proto.v1.Product
	4,  // 21: proto.v1.ProductQuery.List:output_type -> proto.v1.ProductsResult
	5,  // 22: proto.v1.ProductQuery.ById:output_type -> proto.v1.ProductResult
	4,  // 23: proto.v1.ProductQuery.ByKeyword:output_type -> proto.v1.ProductsResult
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_query_proto_init() }
func file_query_proto_init() {
	if File_query_proto != nil {
		return
	}
	file_error_proto_init()
	file_models_proto_init()
	file_query_proto_msgTypes[2].OneofWrappers = []any{
		(*CategoryResult_Category)(nil),
		(*CategoryResult_Error)(nil),
	}
	file_query_proto_msgTypes[5].OneofWrappers = []any{
		(*ProductResult_Product)(nil),
		(*ProductResult_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_query_proto_goTypes,
		DependencyIndexes: file_query_proto_depIdxs,
		MessageInfos:      file_query_proto_msgTypes,
	}.Build()
	File_query_proto = out.File
	file_query_proto_goTypes = nil
	file_query_proto_depIdxs = nil
}
